tabela_periodica = {
    "H": {"nome": "Hidrogênio", "numero_atomico": 1, "massa_atomica": 1.008},
    "He": {"nome": "Hélio", "numero_atomico": 2, "massa_atomica": 4.0026},
    "Li": {"nome": "Lítio", "numero_atomico": 3, "massa_atomica": 6.94},
    "Be": {"nome": "Berílio", "numero_atomico": 4, "massa_atomica": 9.0122},
    "B": {"nome": "Boro", "numero_atomico": 5, "massa_atomica": 10.81},
    "C": {"nome": "Carbono", "numero_atomico": 6, "massa_atomica": 12.011},
    "N": {"nome": "Nitrogênio", "numero_atomico": 7, "massa_atomica": 14.007},
    "O": {"nome": "Oxigênio", "numero_atomico": 8, "massa_atomica": 15.999},
    "F": {"nome": "Flúor", "numero_atomico": 9, "massa_atomica": 18.998},
    "Ne": {"nome": "Neônio", "numero_atomico": 10, "massa_atomica": 20.180},
    "Na": {"nome": "Sódio", "numero_atomico": 11, "massa_atomica": 22.990},
    "Mg": {"nome": "Magnésio", "numero_atomico": 12, "massa_atomica": 24.305},
    "Al": {"nome": "Alumínio", "numero_atomico": 13, "massa_atomica": 26.982},
    "Si": {"nome": "Silício", "numero_atomico": 14, "massa_atomica": 28.085},
    "P": {"nome": "Fósforo", "numero_atomico": 15, "massa_atomica": 30.974},
    "S": {"nome": "Enxofre", "numero_atomico": 16, "massa_atomica": 32.06},
    "Cl": {"nome": "Cloro", "numero_atomico": 17, "massa_atomica": 35.45},
    "Ar": {"nome": "Argônio", "numero_atomico": 18, "massa_atomica": 39.948},
    "K": {"nome": "Potássio", "numero_atomico": 19, "massa_atomica": 39.098},
    "Ca": {"nome": "Cálcio", "numero_atomico": 20, "massa_atomica": 40.078},
    "Sc": {"nome": "Escândio", "numero_atomico": 21, "massa_atomica": 44.956},
    "Ti": {"nome": "Titânio", "numero_atomico": 22, "massa_atomica": 47.867},
    "V": {"nome": "Vanádio", "numero_atomico": 23, "massa_atomica": 50.942},
    "Cr": {"nome": "Cromo", "numero_atomico": 24, "massa_atomica": 51.996},
    "Mn": {"nome": "Manganês", "numero_atomico": 25, "massa_atomica": 54.938},
    "Fe": {"nome": "Ferro", "numero_atomico": 26, "massa_atomica": 55.845},
    "Co": {"nome": "Cobalto", "numero_atomico": 27, "massa_atomica": 58.933},
    "Ni": {"nome": "Níquel", "numero_atomico": 28, "massa_atomica": 58.693},
    "Cu": {"nome": "Cobre", "numero_atomico": 29, "massa_atomica": 63.546},
    "Zn": {"nome": "Zinco", "numero_atomico": 30, "massa_atomica": 65.38},
    "Ga": {"nome": "Gálio", "numero_atomico": 31, "massa_atomica": 69.723},
    "Ge": {"nome": "Germânio", "numero_atomico": 32, "massa_atomica": 72.63},
    "As": {"nome": "Arsênio", "numero_atomico": 33, "massa_atomica": 74.922},
    "Se": {"nome": "Selênio", "numero_atomico": 34, "massa_atomica": 78.971},
    "Br": {"nome": "Bromo", "numero_atomico": 35, "massa_atomica": 79.904},
    "Kr": {"nome": "Criptônio", "numero_atomico": 36, "massa_atomica": 83.798},
    "Rb": {"nome": "Rubídio", "numero_atomico": 37, "massa_atomica": 85.468},
    "Sr": {"nome": "Estrôncio", "numero_atomico": 38, "massa_atomica": 87.62},
    "Y": {"nome": "Ítrio", "numero_atomico": 39, "massa_atomica": 88.906},
    "Zr": {"nome": "Zircônio", "numero_atomico": 40, "massa_atomica": 91.224},
    "Nb": {"nome": "Nióbio", "numero_atomico": 41, "massa_atomica": 92.906},
    "Mo": {"nome": "Molibdênio", "numero_atomico": 42, "massa_atomica": 95.95},
    "Tc": {"nome": "Tecnécio", "numero_atomico": 43, "massa_atomica": 98},
    "Ru": {"nome": "Rutênio", "numero_atomico": 44, "massa_atomica": 101.07},
    "Rh": {"nome": "Ródio", "numero_atomico": 45, "massa_atomica": 102.91},
    "Pd": {"nome": "Paládio", "numero_atomico": 46, "massa_atomica": 106.42},
    "Ag": {"nome": "Prata", "numero_atomico": 47, "massa_atomica": 107.87},
    "Cd": {"nome": "Cádmio", "numero_atomico": 48, "massa_atomica": 112.41},
    "In": {"nome": "Índio", "numero_atomico": 49, "massa_atomica": 114.82},
    "Sn": {"nome": "Estanho", "numero_atomico": 50, "massa_atomica": 118.71},
    "Sb": {"nome": "Antimônio", "numero_atomico": 51, "massa_atomica": 121.76},
    "Te": {"nome": "Telúrio", "numero_atomico": 52, "massa_atomica": 127.60},
    "I": {"nome": "Iodo", "numero_atomico": 53, "massa_atomica": 126.90},
    "Xe": {"nome": "Xenônio", "numero_atomico": 54, "massa_atomica": 131.29},
    "Cs": {"nome": "Césio", "numero_atomico": 55, "massa_atomica": 132.91},
    "Ba": {"nome": "Bário", "numero_atomico": 56, "massa_atomica": 137.33},
    "La": {"nome": "Lantânio", "numero_atomico": 57, "massa_atomica": 138.91},
    "Ce": {"nome": "Cério", "numero_atomico": 58, "massa_atomica": 140.12},
    "Pr": {"nome": "Praseodímio", "numero_atomico": 59, "massa_atomica": 140.91},
    "Nd": {"nome": "Neodímio", "numero_atomico": 60, "massa_atomica": 144.24},
    "Pm": {"nome": "Promécio", "numero_atomico": 61, "massa_atomica": 145},
    "Sm": {"nome": "Samário", "numero_atomico": 62, "massa_atomica": 150.36},
    "Eu": {"nome": "Európio", "numero_atomico": 63, "massa_atomica": 151.96},
    "Gd": {"nome": "Gadolínio", "numero_atomico": 64, "massa_atomica": 157.25},
    "Tb": {"nome": "Térbio", "numero_atomico": 65, "massa_atomica": 158.93},
    "Dy": {"nome": "Disprósio", "numero_atomico": 66, "massa_atomica": 162.50},
    "Ho": {"nome": "Hólmio", "numero_atomico": 67, "massa_atomica": 164.93},
    "Er": {"nome": "Érbio", "numero_atomico": 68, "massa_atomica": 167.26},
    "Tm": {"nome": "Túlio", "numero_atomico": 69, "massa_atomica": 168.93},
    "Yb": {"nome": "Itérbio", "numero_atomico": 70, "massa_atomica": 173.05},
    "Lu": {"nome": "Lutécio", "numero_atomico": 71, "massa_atomica": 174.97},
    "Hf": {"nome": "Háfnio", "numero_atomico": 72, "massa_atomica": 178.49},
    "Ta": {"nome": "Tântalo", "numero_atomico": 73, "massa_atomica": 180.95},
    "W": {"nome": "Tungstênio", "numero_atomico": 74, "massa_atomica": 183.84},
    "Re": {"nome": "Rênio", "numero_atomico": 75, "massa_atomica": 186.21},
    "Os": {"nome": "Ósmio", "numero_atomico": 76, "massa_atomica": 190.23},
    "Ir": {"nome": "Irídio", "numero_atomico": 77, "massa_atomica": 192.22},
    "Pt": {"nome": "Platina", "numero_atomico": 78, "massa_atomica": 195.08},
    "Au": {"nome": "Ouro", "numero_atomico": 79, "massa_atomica": 196.97},
    "Hg": {"nome": "Mercúrio", "numero_atomico": 80, "massa_atomica": 200.59},
    "Tl": {"nome": "Tálio", "numero_atomico": 81, "massa_atomica": 204.38},
    "Pb": {"nome": "Chumbo", "numero_atomico": 82, "massa_atomica": 207.2},
    "Bi": {"nome": "Bismuto", "numero_atomico": 83, "massa_atomica": 208.98},
    "Po": {"nome": "Polônio", "numero_atomico": 84, "massa_atomica": 209},
    "At": {"nome": "Astato", "numero_atomico": 85, "massa_atomica": 210},
    "Rn": {"nome": "Radônio", "numero_atomico": 86, "massa_atomica": 222},
    "Fr": {"nome": "Frâncio", "numero_atomico": 87, "massa_atomica": 223},
    "Ra": {"nome": "Rádio", "numero_atomico": 88, "massa_atomica": 226},
    "Ac": {"nome": "Actínio", "numero_atomico": 89, "massa_atomica": 227},
    "Th": {"nome": "Tório", "numero_atomico": 90, "massa_atomica": 232.04},
    "Pa": {"nome": "Protactínio", "numero_atomico": 91, "massa_atomica": 231.04},
    "U": {"nome": "Urânio", "numero_atomico": 92, "massa_atomica": 238.03},
    "Np": {"nome": "Netúnio", "numero_atomico": 93, "massa_atomica": 237},
    "Pu": {"nome": "Plutônio", "numero_atomico": 94, "massa_atomica": 244},
    "Am": {"nome": "Amerício", "numero_atomico": 95, "massa_atomica": 243},
    "Cm": {"nome": "Cúrio", "numero_atomico": 96, "massa_atomica": 247},
    "Bk": {"nome": "Berquélio", "numero_atomico": 97, "massa_atomica": 247},
    "Cf": {"nome": "Califórnio", "numero_atomico": 98, "massa_atomica": 251},
    "Es": {"nome": "Einstênio", "numero_atomico": 99, "massa_atomica": 252},
    "Fm": {"nome": "Férmio", "numero_atomico": 100, "massa_atomica": 257},
    "Md": {"nome": "Mendelévio", "numero_atomico": 101, "massa_atomica": 258},
    "No": {"nome": "Nobélio", "numero_atomico": 102, "massa_atomica": 259},
    "Lr": {"nome": "Laurêncio", "numero_atomico": 103, "massa_atomica": 262},
    "Rf": {"nome": "Rutherfórdio", "numero_atomico": 104, "massa_atomica": 267},
    "Db": {"nome": "Dúbnio", "numero_atomico": 105, "massa_atomica": 270},
    "Sg": {"nome": "Seabórgio", "numero_atomico": 106, "massa_atomica": 271},
    "Bh": {"nome": "Bóhrio", "numero_atomico": 107, "massa_atomica": 270},
    "Hs": {"nome": "Hássio", "numero_atomico": 108, "massa_atomica": 277},
    "Mt": {"nome": "Meitnério", "numero_atomico": 109, "massa_atomica": 278},
    "Ds": {"nome": "Darmstádio", "numero_atomico": 110, "massa_atomica": 281},
    "Rg": {"nome": "Roentgênio", "numero_atomico": 111, "massa_atomica": 282},
    "Cn": {"nome": "Copernício", "numero_atomico": 112, "massa_atomica": 285},
    "Nh": {"nome": "Nihônio", "numero_atomico": 113, "massa_atomica": 286},
    "Fl": {"nome": "Fleróvio", "numero_atomico": 114, "massa_atomica": 289},
    "Mc": {"nome": "Moscóvio", "numero_atomico": 115, "massa_atomica": 290},
    "Lv": {"nome": "Livermório", "numero_atomico": 116, "massa_atomica": 293},
    "Ts": {"nome": "Tenessino", "numero_atomico": 117, "massa_atomica": 294},
    "Og": {"nome": "Oganessônio", "numero_atomico": 118, "massa_atomica": 294}
}

def buscar_elemento(sigla):
    elemento = tabela_periodica.get(sigla.capitalize())
    if elemento:
        print(f"Nome: {elemento['nome']}")
        print(f"Número Atômico: {elemento['numero_atomico']}")
        print(f"Massa Atômica: {elemento['massa_atomica']}")
    else:
        print("Elemento não encontrado.")
sigla = input("Digite a sigla do elemento químico: ")
buscar_elemento(sigla)
